### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int net.xpece.android.support.preference.ListPreference.E'

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#103]
Just got this crash reported, seems to be a new one, only seen with 2.2.0. Can you please take a look at it?
Asus device, SDK 21

```java
Caused by java.lang.NullPointerException: Attempt to read from field 'int net.xpece.android.support.preference.ListPreference.E' on a null object reference
       at net.xpece.android.support.preference.XpListPreferenceDialogFragment.net.xpece.android.support.preference.ListPreference.isSimple(XpListPreferenceDialogFragment.java:1653)
       at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreateDialog(PreferenceDialogFragmentCompat.java:154)
       at android.support.v4.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:328)
       at android.support.v4.app.Fragment.performGetLayoutInflater(Fragment.java:1226)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
       at android.support.v4.app.FragmentActivity.android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentActivity.java:11195)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
       at android.app.Activity.performStart(Activity.java:6048)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3967)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1312)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5290)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```

**Comment by consp1racy** [comment]
Thanks for the report, here's what I think happens:

The dialog expects the preference hierarchy to be already loaded at the time the dialog is created.

What I think is happening:
1) You have a set of preferences..
2) You click a ListPreference and its dialog shows.
3) a) You remove the ListPreference and rotate phone *OR*
 b) **You rotate phone and don't add the ListPreference whose dialog is showing.**
4) The dialog crashes because it can't find its ListPreference in preference tree.

You need to make your preference hierarchy *exactly the same* as it was before orientation change **in onCreatePreferences**.\* Use saved state for that.

\* As you can see in the stack trace the error occurs in Activity.onStart / Fragment.onActivityCreated. It's necessary your preference tree has stabilized before that.

Since this doesn't happen in the sample app, I'll close this issue. It's not the first time your dynamically added preferences are acting up. Unfortunately this is not something I can guard against. If the preference is not there then the dialog has nowhere to get it from.

**Comment by dirkam** [comment]
Your explanation is on point and helped to identify the root cause. Thanks.
