### ISSUE TITLE
ListPreference java.util.DuplicateFormatFlagsException: Flags = ' '

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#104]
Hi,

Got this new crash, seems to be very rare. Can you please check it?
support lib 27.1.1 with 2.2.0
Samsung Android 7.

```java
Fatal Exception: java.util.DuplicateFormatFlagsException: Flags = ' '
       at java.util.Formatter$Flags.parse(Formatter.java:4276)
       at java.util.Formatter$FormatSpecifier.flags(Formatter.java:2680)
       at java.util.Formatter$FormatSpecifier.(Formatter.java:2749)
       at java.util.Formatter$FormatSpecifierParser.(Formatter.java:2591)
       at java.util.Formatter.parse(Formatter.java:2524)
       at java.util.Formatter.format(Formatter.java:2472)
       at java.util.Formatter.format(Formatter.java:2426)
       at java.lang.String.format(String.java:2626)
       at net.xpece.android.support.preference.ListPreference.getSummary(ListPreference.java:506)
       at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:578)
       at net.xpece.android.support.preference.DialogPreference.onBindViewHolder(DialogPreference.java:192)
       at net.xpece.android.support.preference.ListPreference.onBindViewHolder(ListPreference.java:626)
       at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:362)
       at android.support.v7.preference.XpPreferenceGroupAdapter.onBindViewHolder(XpPreferenceGroupAdapter.java:100)
       at android.support.v7.preference.XpPreferenceGroupAdapter.onBindViewHolder(XpPreferenceGroupAdapter.java:16)
       at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
       at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
       at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:18647)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:13752)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
       at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3225)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.findFirstDependency(AppBarLayout.java:1361)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6460)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:785)
       at android.view.View.measure(View.java:21040)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2543)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1610)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1490)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7027)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6688)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by consp1racy** [comment]
This is the code for getSummary:

    /**
     * Returns the summary of this ListPreference. If the summary
     * has a {@linkplain java.lang.String#format String formatting}
     * marker in it (i.e. "%s" or "%1$s"), then the current entry
     * value will be substituted in its place.
     *
     * @return the summary with appropriate string substitution
     */
    @Nullable
    public CharSequence getSummary() {
        CharSequence entry = this.getEntry();
        return this.mSummary == null ? super.getSummary() : String.format(this.mSummary, entry == null ? "" : entry);
    }

Looks like you set summary with what could be interpreted as placeholders by String.format. Perhaps a percent sign followed by a space. Can you confirm this?

If this is the case you'll need to double the percent signs. https://stackoverflow.com/questions/5011932/how-to-escape-in-string-format

**Comment by dirkam** [comment]
Yes, this can happen as this ListPreference has entries populated by user entered values. Thanks.

**Comment by dirkam** [comment]
How should this work? If I use %% then in summary it shows %, but when I click on the preference and the entries are shown then it shows %%.

I can use workarounds here, but this might be a problem for others, too.

**Comment by consp1racy** [comment]
The entries can contain percent signs. The summary has to be escaped.

Case 1: Selected entry is "World", mSummary is "Hello, %s", getSummary returns "Hello, World".
Case 2: Selected entry is "100%", mSummary is "Loading %s", getSummary returns "Loading 100%".
Case 3: Selected entry is "Something", mSummary is "Nothing", getSummary returns "Nothing".
Case 4: Selected entry is "100", mSummary is "%s%", getSummary throws the mentioned exception.
Case 5: Selected entry is "100", mSummary is "%s%%", getSummary returns "100%".

So if you have percent signs in strings assigned by android:summary you need to double them. If you call setSummary in java after manually composing the summary text you need to double any percent signs.

I hope I made it clear enough, let me know if you need any further assistance.

---

> this might be a problem for others, too.

I understand, but this is how the platform and support library behaves and I don't intend to deviate from that.

**Comment by dirkam** [comment]
Yes, this is what I came up with, too.
