### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError: android.view.View.getTextAlignment

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#110]
If `style="@style/Preference.Material.DialogPreference.ListPreference.SimpleMenu"` is used of a `ListPreference` then it crashes on 4.0.3 and 4.0.4 devices. I think it should fallback to simple dialog on these API levels.

**Comment by consp1racy** [comment]
Please post the full stacktrace. SimpleMenu was always compatible even with Android 2.3. I'll just ensure I use the public SDK and check the method call.

**Comment by dirkam** [comment]
```java
Fatal Exception: java.lang.NoSuchMethodError: android.view.View.getTextAlignment
       at net.xpece.android.support.preference.ListPreference.showAsPopup(ListPreference.java:329)
       at net.xpece.android.support.preference.ListPreference.performClick(ListPreference.java:170)
       at android.support.v7.preference.Preference$1.onClick(Preference.java:170)
       at android.view.View.performClick(View.java:3521)
       at android.view.View$PerformClick.run(View.java:14185)
       at android.os.Handler.handleCallback(Handler.java:605)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4464)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:589)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by consp1racy** [comment]
I see it now, for some reason I had suppressed this particular error at compiled time. This was a mistake. It will be fixed in the next version.

Try it out now: https://jitpack.io/#consp1racy/android-support-preference/e4c6b9e3c5
