### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException: no such column: is_ringtone_theme

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#117]
Hi,

I get the following crash reports (can't reproduce) using 2.3.2:

```java
Fatal Exception: android.database.sqlite.SQLiteException: no such column: is_ringtone_theme (code 1): , while compiling: SELECT _id, title, "content://media/internal/audio/media", title_key FROM audio WHERE ((is_alarm=1 or is_ringtone=1) and _size!=0 and is_ringtone_theme!=1 and is_notification_theme!=1 and is_alarm_theme!=1) ORDER BY title_key
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
	(no such column: is_ringtone_theme (code 1): , while compiling: SELECT _id, title, "content://media/internal/audio/media", title_key FROM audio WHERE ((is_alarm=1 or is_ringtone=1) and _size!=0 and is_ringtone_theme!=1 and is_notification_theme!=1 and is_alarm_theme!=1) ORDER BY title_key)
#################################################################
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:179)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:760)
       at android.content.ContentResolver.query(ContentResolver.java:710)
       at android.content.ContentResolver.query(ContentResolver.java:668)
       at android.app.Activity.managedQuery(Activity.java:2607)
       at android.media.RingtoneManager.query(RingtoneManager.java:770)
       at android.media.RingtoneManager.query(RingtoneManager.java:760)
       at android.media.RingtoneManager.getInternalRingtones(RingtoneManager.java:639)
       at android.media.RingtoneManager.getCursor(RingtoneManager.java:455)
       at net.xpece.android.support.preference.RingtoneManagerCompat.getCursor(RingtoneManagerCompat.java:86)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.loadRingtoneManager(XpRingtonePreferenceDialogFragment.java:1224)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
       at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
       at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
       at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

![image](https://user-images.githubusercontent.com/6302839/52221155-da11f880-28a0-11e9-991b-6882d4bd03ef.png)

Can you please look into this?

Thank you!

**Comment by consp1racy** [comment]
A customized `RingtoneManager` expects the `MediaProvider` (both are part of the OS) these `is_*_theme` columns, but they're not there. These columns are not metioned in AOSP.

Is this report from rooted phones?

This is what I found:

https://github.com/consp1racy/SPay-inner-workings/blob/master/boot.oat_files/arm64/dex/out0/android/media/RingtoneManager.java

I think I can work around it. But I don't have a Samsung phone and I don't know how these themes work and how they integrate with ringtone manager. Whatever I do, it may have side effects.

**Comment by consp1racy** [comment]
You know what, I'll just fall back to the system picker. There are too many unknowns.

Will be in 2.4.0.

In the meantime you can get it from jitpack.io: https://jitpack.io/#consp1racy/android-support-preference/c646d2bd5e

**Comment by dirkam** [comment]
Thank you, fallback could be just fine, I guess.
According to the reports, none of these devices are rooted.
