### ISSUE TITLE
RingtonePreference ActivityNotFoundException

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#17]
Can you please take a look at this?

``` java
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.RINGTONE_PICKER (has extras) }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1817)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1632)
    at android.app.Activity.startActivityFromFragment(Activity.java:4630)
    at android.app.Fragment.startActivityForResult(Fragment.java:1114)
    at android.app.Fragment.startActivityForResult(Fragment.java:1098)
    at android.preference.RingtonePreference.onClick(RingtonePreference.java:168)
    at android.preference.Preference.performClick(Preference.java:1163)
    at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:269)
    at android.widget.AdapterView.performItemClick(AdapterView.java:339)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3721)
    at android.widget.AbsListView$3.run(AbsListView.java:5660)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by consp1racy** [comment]
Hello, this has nothing to do with my library. As you can see here

```
android.preference.RingtonePreference
```

you're using the native preference framework.

If you'd like to use this library, please read https://github.com/consp1racy/android-support-preference#how-to-use-the-library

**Comment by dirkam** [comment]
You are absolutely right, sorry for this.
