### ISSUE TITLE
java.lang.IllegalStateException: No cursor that can return names

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#30]
Can you please take a look at this? I'm using RingtonePreference and I get this crash from time to time.
I can't reproduce it on my own. Using 0.8.0, but I got this with 0.6.2 as well.

``` java
Fatal Exception: java.lang.IllegalStateException: No cursor that can return names
       at net.xpece.android.support.preference.SortCursor.getColumnNames(SortCursor.java:253)
       at android.database.AbstractCursor.getColumnIndex(AbstractCursor.java:283)
       at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:300)
       at android.support.v4.widget.CursorAdapter.init$f13d381(CursorAdapter.java:174)
       at android.support.v4.widget.CursorAdapter.(CursorAdapter.java)
       at android.support.v4.widget.ResourceCursorAdapter.(ResourceCursorAdapter.java)
       at android.support.v4.widget.SimpleCursorAdapter.(SimpleCursorAdapter.java)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.onPrepareDialogBuilder(XpRingtonePreferenceDialogFragment.java:195)
       at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreateDialog(PreferenceDialogFragmentCompat.java:151)
       at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4867)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by consp1racy** [comment]
Can you tell anything about the conditions when this happens? Devices, API levels, etc.?

If it happens again look for warnings in LogCat about `NoSuchFieldException` or `IllegalAccessException` and post it here along with device on which it happened.

**Comment by dirkam** [comment]
Samsung GT-S7710, 4.1.2
Lenovo A6000 4.4.4
No Root.

**Comment by consp1racy** [comment]
I made it so it will not crash. No ringtones will be shown in that case except "empty" and "default" if those are enabled in XML attributes. Is this good enough?

**Comment by dirkam** [comment]
It's better. What can be the reason for this? I tried it with an emulator where there are no built-in ringtones at all, and I could not reproduce this issue.

Btw, how can I specify these in XML? I don't specify anything and I have the "default" option, which is fine for me.

**Comment by consp1racy** [comment]
These are attributes and their default values for `RingtonePreference`:

```
<item name="android:ringtoneType">ringtone</item>
<item name="android:showSilent">true</item>
<item name="android:showDefault">true</item>
```

Another alternative would be to try and open system picker if this happens. Let me try that instead.

**Comment by dirkam** [comment]
Indeed, it sounds better. If that fails as well then something is really messed up.

**Comment by consp1racy** [comment]
New version will be released momentarily.

**Comment by dirkam** [comment]
Awesome. 0.8.1 works like a charm. Thanks for your prompt help.
