### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#31]
I got a few crash reports like this, using 0.6.2 and 0.8.0. Can you please a take a look at it? Do you happen to have any idea how can I avoid it?

``` java
Fatal Exception: java.lang.NullPointerException
       at android.content.res.XmlBlock.nativeGetStyleAttribute(XmlBlock.java)
       at android.content.res.XmlBlock.access$1400(XmlBlock.java:34)
       at android.content.res.XmlBlock$Parser.getStyleAttribute(XmlBlock.java:440)
       at android.widget.TextView.(TextView.java:666)
       at android.widget.EditText.(EditText.java:65)
       at android.widget.EditText.(EditText.java:61)
       at android.support.v7.widget.AppCompatEditText.(AppCompatEditText.java:60)
       at android.support.v7.widget.AppCompatEditText.(AppCompatEditText.java:56)
       at net.xpece.android.support.preference.XpEditTextPreferenceDialogFragment.net.xpece.android.support.preference.EditTextPreference.createEditText(XpEditTextPreferenceDialogFragment.java:2067)
       at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreateDialog(PreferenceDialogFragmentCompat.java:143)
       at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:308)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5595)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```

**Comment by consp1racy** [comment]
What API level did this happen on? What version of support libs are you using?

**Comment by dirkam** [comment]
HUAWEI CRR-L09 - 5.1.1
CHM-U01 - 5.1.1
ALE-L21 - 5.0.1
HUAWEI NXT-L29 - 6.0

**Comment by consp1racy** [comment]
The stack trace above - which of these precisely is it from?

Also post how you use EditTextPreference.

Make sure your preference activity uses AppCompat theme.

**Comment by dirkam** [comment]
It's from HUAWEI CRR-L09 - 5.1.1.

I use AppCompat for preference activity. What exactly you need to see regarding EditTextPreference?

**Comment by consp1racy** [comment]
> What exactly you need to see regarding EditTextPreference?

How you use it in preference XML.

Because I take all attributes from EditTextPreference and apply them to the EditText inside dialog. 

---

Ok, there's no mention of `getStyleAttribute` in `TextView` from AOSP API 22 (Android 5.1.1) so I officially have no idea how to prevent this. Manufacturers altered `TextView` in a way that causes this error and unless I find the source code I have no means to combat this.

**Comment by dirkam** [comment]
``` java
<EditTextPreference xmlns:app="http://schemas.android.com/apk/res-auto"
                android:dialogTitle="@string/dialogTitle"
                android:key="key"
                android:summary="@string/summary"
                android:title="@string/title"
                app:asp_iconPaddingEnabled="false" />

import net.xpece.android.support.preference.EditTextPreference;

EditTextPreference mPreference;

mPreference = (EditTextPreference) findPreference("key");

```

**Comment by consp1racy** [comment]
I have a clue to what's happening. Caching `AttributeSet` from `EditTextPreference` and using it later to create `EditText` inside the dialog is not the way to go since it might have been invalidated in the meantime.

**Comment by dirkam** [comment]
I guess this is something that can only be handled on your end? Do I have any option to have some kind of a workaround? Thanks.

**Comment by consp1racy** [comment]
Actually yes, you can work around this on your end until I fix this.

Subclass `EditTextPreference` and override `createEditText(Context)`:

```
@Override
public EditText createEditText(Context context) {
    EditText editText = new AppCompatEditText(context);

    // Give it an ID so it can be saved/restored
    editText.setId(android.R.id.edit);

    // Do whatever additional setup you need.

    return editText;
}
```

In your preference XML use fully qualified name of your new class.

**Comment by dirkam** [comment]
Thanks for the update.

May I ask when do you plan to release a new version with the fix?

**Comment by consp1racy** [comment]
As soon as I investigate https://github.com/consp1racy/android-support-preference/issues/30

**Comment by dirkam** [comment]
Thank you, can you please confirm that I can still use this workaround for the time being?

**Comment by consp1racy** [comment]
Workaround above is very much valid. 

In both new version and the workaround `EditText` attributes on `EditTextPreference` won't be honored. If you need to alter e.g. input type you have to do it in `createEditText`. 

Next release will introduce `OnEditTextCreatedListener` which will allow you to setup `EditText` without subclassing `EditTextPreference`.

There is a chance the original behavior (reading attributes from XML) will return in the future but for now it's too much work.
