### ISSUE TITLE
Ringtone permissions

### ISSUE THREAD

**Issue by consp1racy** [consp1racy/android-support-preference#38]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.liveultrahealthy.violet/com.liveultrahealthy.violet.ui.settings.SettingsActivity}: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media/50 from pid=19062, uid=10187 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
       at android.content.ContentResolver.query(ContentResolver.java:513)
       at android.content.ContentResolver.query(ContentResolver.java:448)
       at com.lge.media.RingtoneManagerEx.getActualDefaultRingtoneUri(RingtoneManagerEx.java:244)
       at android.media.RingtoneEx.getTitle(RingtoneEx.java:177)
       at android.media.RingtoneEx.getTitle(RingtoneEx.java:145)
       at com.liveultrahealthy.violet.ui.settings.SettingsFragment$1.onPreferenceChange(SettingsFragment.java:65)
       at com.liveultrahealthy.violet.ui.settings.SettingsFragment.bindPreferenceSummaryToValue(SettingsFragment.java:80)
       at com.liveultrahealthy.violet.ui.settings.SettingsFragment.onCreatePreferences2(SettingsFragment.java:152)
       at android.support.v7.preference.XpPreferenceFragment.onCreatePreferences(XpPreferenceFragment.java:53)
       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:216)
       at com.liveultrahealthy.violet.ui.settings.SettingsFragment.onCreate(SettingsFragment.java:102)
...
```

Device: LG H634
Android 5.1.1

**Comment by dirkam** [comment]
Do we have any workaround for this?
Lately I see more and more crashing sessions because of this issue.

**Comment by consp1racy** [comment]
Yeah, me too, just about yesterday I grew tired of it and just wrapped the `Ringtone.getTitle` call in try-catch and just set the summary to `"???"` if it fails.

Here's what I found out:
1) This will happen when the user has a default ringtone from external storage and the app is not granted the `READ_EXTERNAL_STORAGE` permission. Those are apps that do not specify it in their manifest below API 23 and apps over API 23 that have not been granted the runtime permission.
2) For devices with API <23 just request the permission in manifest. It will solve you a lot of headaches, not just this one. For example Samsung Gallery doesn't grant you URI permissions when obtaining images, so you have to rely on the manifest permission anyway to actually read the image.
3) On API 23+ there are two cases:
  a) The user has granted you `READ_EXTERNAL_STORAGE` permission, set a ringtone from external storage and then revoked the permission. You can work around this one by also saving the ringtone title when it's picked.
  b) The user hasn't granted you the runtime permission yet so you have no means of getting the ringtone title. And you don't want to flash the Permission dialog for no apparent reason. This one really is a bitch.

**Comment by dirkam** [comment]
In my case I have `READ_EXTERNAL_STORAGE` in manifest, so it's fine on older APIs.
I don't do anything with ringtones until the user picks one with `RingtonePreference`.
Based on what you describe I should maybe try to get the title of the default ringtone with
```
RingtoneManager.getRingtone(context, RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE)).getTitle(context);
```
in a try-catch before `XpRingtonePreferenceDialogFragment` is shown and if the exception is thrown the permission should be asked for, correct?

**Comment by consp1racy** [comment]
The ringtone picker only lists ringtones from external storage if the permission is already granted. There's no problem there.

The problem is that `RingtoneManager.getDefaultUri(RingtoneManager.TYPE_RINGTONE))` may be located on external storage. `getTitle` would then throw.

I don't think it's good practice to open the permission dialog automatically when the user opens the settings. Maybe ask for the permission before opening the ringtone picker. But that still involves having the `"???"` or some other placeholder string when the permission is not granted upon first entry.

I'm afraid I have no best answer.

**Comment by dirkam** [comment]
> The ringtone picker only lists ringtones from external storage if the permission is already granted. There's no problem there.

There must be as this is where my app crashes. I don't do anything with ringtones, I only let the user select one with `RingtonePreference`

```
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/media from pid=, uid= requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
    at android.os.Parcel.readException (Parcel.java:1620)
    at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:183)
    at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
    at android.content.ContentProviderProxy.query (ContentProviderNative.java:421)
    at android.content.ContentResolver.query (ContentResolver.java:493)
    at android.content.ContentResolver.query (ContentResolver.java:435)
    at android.media.RingtoneManager.getUriFromPath (RingtoneManager.java:951)
    at android.media.RingtoneManager.getActualDefaultRingtoneUri (RingtoneManager.java:755)
    at android.media.RingtoneManager.getRingtone (RingtoneManager.java:1163)
    at android.media.RingtoneManager.getRingtone (RingtoneManager.java:688)
    at net.xpece.android.support.preference.x.run (XpRingtonePreferenceDialogFragment.java:410)
    at android.os.Handler.handleCallback (Handler.java:739)
    at android.os.Handler.dispatchMessage (Handler.java:95)
    at android.os.Looper.loop (Looper.java:148)
    at android.app.ActivityThread.main (ActivityThread.java:5418)
    at java.lang.reflect.Method.invoke (Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)
```

**Comment by consp1racy** [comment]
Oh crap, you're right, the picker crashes when trying to play the default ringtone from external storage.

I'll make it go quiet by default but I'll try to provide a pluggable listener so you can open permissions dialog when that happens.

**Comment by dirkam** [comment]
I thought we were talking about the same, but I'm glad that the stacktrace helped to identify the issue.
So until you prepare a new release I guess we can use the method I described in the previous post (checking if exception is shown when trying to get title before actually showing the picker).

**Comment by consp1racy** [comment]
I just pushed v1.3.0. See https://github.com/consp1racy/android-support-preference/blob/master/CHANGELOG.md.

The picker will not crash. On top of that you can now set a listener in case something's wrong and handle the situation gracefully.

    @Override
    public void onCreatePreferences2(final Bundle savedInstanceState, final String rootKey) {
        // ...

        ((RingtonePreference) findPreference("notifications_new_message_ringtone")).setOnFailedToReadRingtoneListener(new RingtonePreference.OnFailedToReadRingtoneListener() {
            @Override
            public void onFailedToReadRingtone(final RingtonePreference ringtonePreference, final boolean cannotPlayDefault, final boolean cannotShowTitleSelected) {
                final Intent i = ringtonePreference.buildRingtonePickerIntent();
                try {
                    startActivityForResult(i, 746);
                } catch (ActivityNotFoundException ex) {
                    // There's no ringtone picker on the device? Oh well...
                    ringtonePreference.showDialogFragment(SettingsFragment.this);
                }
            }
        });

        // ...
    }

    @Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == 746 && resultCode == Activity.RESULT_OK) {
            ((RingtonePreference) findPreference("notifications_new_message_ringtone")).onActivityResult(data);
        }
    }

In this example I decided to open the system ringtone picker because that doesn't need additional permissions. System picker however does not use your app's theme. You can instead ask for the permission, of course.

You also have to handle setting ringtone preference summary in a way that doesn't crash:

```
if (preference instanceof RingtonePreference) {
    // For ringtone preferences, look up the correct display value using RingtoneManager.
    if (TextUtils.isEmpty(stringValue)) {
        // Empty values correspond to 'silent' (no ringtone).
        preference.setSummary(R.string.pref_ringtone_silent);
    } else {
        final Uri selectedUri = Uri.parse(stringValue);
        try {
            final Ringtone ringtone = RingtoneManager.getRingtone(
                preference.getContext(), selectedUri);
            if (ringtone == null) {
                // Clear the summary if there was a lookup error, i.e. does not exist.
                preference.setSummary(null);
            } else {
                // Set the summary to reflect the new ringtone display name.
                final String name = ringtone.getTitle(preference.getContext());
                preference.setSummary(name);
            }
        } catch (SecurityException ex) {
            // The user has selected a ringtone from external storage
            // and then revoked READ_EXTERNAL_STORAGE permission.
            // We have no way of guessing the ringtone title.
            // We'd have to store the title of selected ringtone in prefs as well.
            preference.setSummary("???");
        }
    }
}
```

**Comment by consp1racy** [comment]
@dirkam Please update to 1.3.1. There was a NullPointerException possibility in 1.3.0.
