### ISSUE TITLE
0.9.1 with ProGuard: InflateException

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#41]
Tried to update to 0.9.1. It works fine with debug builds but once I generate a signed APK with ProGuard enabled I get the following error when I test the app. Can you please take a look at it? Is this something on my end or something with this release of the library? With 0.8.1 it is working fine with ProGuard as well.

Thanks!

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{.SettingsActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class ListPreference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.access$600(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.InflateException: Binary XML file line #13: Error inflating class ListPreference
       at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:263)
       at android.support.v7.preference.PreferenceInflater.onCreateItem(PreferenceInflater.java:2281)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:359)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:361)
       at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:167)
       at android.support.v7.preference.PreferenceInflater.inflate$7af30e91(PreferenceInflater.java:117)
       at android.support.v7.preference.XpPreferenceManager.inflateFromResource$6154c3e6(XpPreferenceManager.java:72)
```

**Comment by consp1racy** [comment]
Hi, can you check if version 0.9.0 has the same problem? Please post the whole stack trace, this isn't everything. Also post the preference file, maybe there's an error there.

---

Version 0.9.1 has a dependency on support libs version 21.1.0 which is broken. If you do not already please specify version 24.1.1 in your project directly like so:

```
ext.supportLibVersion = "24.1.1"
compile "com.android.support:design:$supportLibVersion"
compile "com.android.support:preference-v7:$supportLibVersion"
```

This may or may not fix the issue. Please report if it does.

**Comment by dirkam** [comment]
I use 24.1.1 version of the support library.
0.9.0 crashes as well.

Stacktrace:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.my.app.SettingsActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class ListPreference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2071)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.access$600(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.view.InflateException: Binary XML file line #13: Error inflating class ListPreference
       at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:263)
       at android.support.v7.preference.PreferenceInflater.onCreateItem(PreferenceInflater.java:2281)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:359)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:361)
       at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:167)
       at android.support.v7.preference.PreferenceInflater.inflate$7af30e91(PreferenceInflater.java:117)
       at android.support.v7.preference.XpPreferenceManager.inflateFromResource$6154c3e6(XpPreferenceManager.java:72)
       at com.my.app.SettingsFragment.android.support.v7.preference.PreferenceFragmentCompat.addPreferencesFromResource(SettingsFragment.java:6423)
       at android.support.v7.preference.XpPreferenceFragment.onCreatePreferences(XpPreferenceFragment.java:54)
       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:218)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2062)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
       at com.instabug.library.compat.InstabugAppCompatActivity.onStart(InstabugAppCompatActivity.java:18)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
       at android.app.Activity.performStart(Activity.java:5018)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2044)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.access$600(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:256)
       at android.support.v7.preference.PreferenceInflater.onCreateItem(PreferenceInflater.java:2281)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:359)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:361)
       at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:167)
       at android.support.v7.preference.PreferenceInflater.inflate$7af30e91(PreferenceInflater.java:117)
       at android.support.v7.preference.XpPreferenceManager.inflateFromResource$6154c3e6(XpPreferenceManager.java:72)
       at com.my.app.SettingsFragment.android.support.v7.preference.PreferenceFragmentCompat.addPreferencesFromResource(SettingsFragment.java:6423)
       at android.support.v7.preference.XpPreferenceFragment.onCreatePreferences(XpPreferenceFragment.java:54)
       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:218)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2062)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
       at com.instabug.library.compat.InstabugAppCompatActivity.onStart(InstabugAppCompatActivity.java:18)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
       at android.app.Activity.performStart(Activity.java:5018)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2044)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.access$600(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f01022d a=4}
       at android.content.res.Resources.loadColorStateList(Resources.java:2040)
       at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
       at net.xpece.android.support.preference.PreferenceIconHelper.getTintList(PreferenceIconHelper.java:78)
       at net.xpece.android.support.preference.PreferenceIconHelper.loadFromAttributes(PreferenceIconHelper.java:60)
       at net.xpece.android.support.preference.DialogPreference.init(DialogPreference.java:1061)
       at net.xpece.android.support.preference.ListPreference.(ListPreference.java)
       at net.xpece.android.support.preference.ListPreference.(ListPreference.java)
       at net.xpece.android.support.preference.ListPreference.(ListPreference.java)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:256)
       at android.support.v7.preference.PreferenceInflater.onCreateItem(PreferenceInflater.java:2281)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:359)
       at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:361)
       at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:167)
       at android.support.v7.preference.PreferenceInflater.inflate$7af30e91(PreferenceInflater.java:117)
       at android.support.v7.preference.XpPreferenceManager.inflateFromResource$6154c3e6(XpPreferenceManager.java:72)
       at com.my.app.SettingsFragment.android.support.v7.preference.PreferenceFragmentCompat.addPreferencesFromResource(SettingsFragment.java:6423)
       at android.support.v7.preference.XpPreferenceFragment.onCreatePreferences(XpPreferenceFragment.java:54)
       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:218)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2062)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
       at com.instabug.library.compat.InstabugAppCompatActivity.onStart(InstabugAppCompatActivity.java:18)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
       at android.app.Activity.performStart(Activity.java:5018)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2044)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2096)
       at android.app.ActivityThread.access$600(ActivityThread.java:138)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:4787)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by consp1racy** [comment]
This library is a work in progress and even minor releases bring breaking changes which are described in the changelog. Focus on this
- `asp_preferenceIconTint` is back along with `asp_preferenceDialogIconTint`.
  - You _have to_ define these attributes in your theme. 
  - Recommended colors are either `?colorAccent` or `?colorControlNormal`.

```
<item name="asp_preferenceIconTint">?colorAccent</item>
<item name="asp_preferenceDialogIconTint">?asp_preferenceIconTint</item>
```

**Comment by dirkam** [comment]
it works, thanks!
