### ISSUE TITLE
Target fragment must implement TargetFragment interface

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#65]
This might be something on my end, but may I ask for your help with the following crash?

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.my.app.SettingsActivity}: java.lang.IllegalStateException: Target fragment must implement TargetFragment interface
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2491)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2564)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4160)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1447)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
Caused by java.lang.IllegalStateException: Target fragment must implement TargetFragment interface
       at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreate(PreferenceDialogFragmentCompat.java:80)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.onCreate(XpRingtonePreferenceDialogFragment.java:125)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
       at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1294)
       at android.support.v4.app.Fragment.onCreate(Fragment.java:1265)
       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:205)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2893)
       at android.support.v4.app.FragmentActivity.android.support.v4.app.FragmentController.dispatchCreate(FragmentActivity.java:8190)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at com.my.app.SettingsActivity.onCreate(SettingsActivity.java:52)
       at android.app.Activity.performCreate(Activity.java:6030)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2564)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4160)
       at android.app.ActivityThread.access$900(ActivityThread.java:170)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1447)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5576)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
```

Previously I used my preferences xml to add a few `RingtonePreference`. Recently I changed to use one `RingtonePreference` and override `onDisplayPreferenceDialog` to show a dialog where the user can select among the items and depending on the selection `XpRingtonePreferenceDialogFragment` is shown to select ringtones.
This is how it is done:
```java
ringtonePreference.setRingtoneType(RingtoneManager.TYPE_RINGTONE);
                                    XpRingtonePreferenceDialogFragment ringtonePicker = XpRingtonePreferenceDialogFragment.newInstance(ringtonePreference.getKey());
                                    ringtonePicker.setTargetFragment(SettingsFragment.this, 0);
                                    ringtonePicker.show(getChildFragmentManager(), DIALOG_FRAGMENT_TAG);
```
`SettingsFragment` extends `XpPreferenceFragment`

It is working fine but I can see a few crashes reported (can't reproduce it).
So far the crashes are from `Android 5, 6, 7` and `Samsung J3, S7 Edge, LG G Pad`

This is with `net.xpece.android:support-preference:1.2.6`

Any help would be highly appreciated.

**Comment by consp1racy** [comment]
1) Start by *NOT* using `getChildFragmentManager()`. Use `getFragmentManager()`. There's no `SettingsFragment.this` in child manager of `SettingsFragment.this` so the `XpRingtonePreferenceDialogFragment` can't target it.

2) Upgrade to 1.2.7 to avoid [this issue](http://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3/42957234#42957234).

**Comment by dirkam** [comment]
Thank you very much for your comment on this.
I'll try to use `getFragmentManager()`.
