### ISSUE TITLE
PreferenceScreen cannot be cast to DialogPreference

### ISSUE THREAD

**Issue by goldmont** [consp1racy/android-support-preference#66]
Hi,

I'm using the latest version of this library and I'm trying to add preferences dynamically from the onCreate method of the Fragment. I'm still not able to solve the following error:

```
java.lang.ClassCastException: android.support.v7.preference.PreferenceScreen cannot be cast to android.support.v7.preference.DialogPreference
                                                                                at android.support.v7.preference.PreferenceDialogFragmentCompat.onCreate(PreferenceDialogFragmentCompat.java:89)
                                                                                at android.support.v4.app.Fragment.performCreate(Fragment.java:2180)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1244)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                                at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

In past I run the same code using standard Android Fragments (android.preference.PreferenceFragment) and it worked like a charm but now, using v7 Fragments, it crashes when I tap on the ListPreference. The CheckBoxPreference works fine. The code is the following:

```java
public static class PreferencesFragment extends XpPreferenceFragment {

        @Override
        public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);
            RecyclerView mRecyclerView = getListView();
            mRecyclerView.setFocusable(false);
        }

        @Override
        public void onCreatePreferences2(Bundle savedInstanceState, String rootKey) {
            addPreferencesFromResource(R.xml.preferences_container);
            
            PreferenceScreen mPreferenceScreen = getPreferenceScreen();
            
            PreferenceCategory category = new PreferenceCategory(mPreferenceScreen.getContext());
            category.setTitle("Preference Category");
            
            mPreferenceScreen.addPreference(category);
            
            CheckBoxPreference checkBoxPreference = new CheckBoxPreference(mPreferenceScreen.getContext());
            checkBoxPreference.setTitle("CheckBox Title");
            checkBoxPreference.setSummary("CheckBox Summary");
            
            category.addPreference(checkBoxPreference);
            
            ListPreference listPreference = new ListPreference(mPreferenceScreen.getContext());
            listPreference.setTitle("List Title");
            listPreference.setSummary("%s");
            String[] entries = new String[] {"Entry 1", "Entry 2", "Entry 3"};
            String[] entryValues = new String[] {"1", "2", "3"};
            listPreference.setEntries(entries);
            listPreference.setEntryValues(entryValues);
            
            category.addPreference(listPreference);
        }

    }
```

R.xml.preferences_container:
```xml
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen />
```

Styles.xml:
```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="preferenceTheme">@style/PreferenceThemeOverlay.Material</item>
        <item name="asp_preferenceIconTint">?colorAccent</item>
        <item name="asp_preferenceDialogIconTint">?asp_preferenceIconTint</item>
    </style>

</resources>
```

Could you help me? Thank you in advance!

**Comment by consp1racy** [comment]
I don't see anything suspicious right now, except make sure you use preference classes from the  `net.xpece.android.support.preference` not `android.support.v7.preference`.

**Comment by goldmont** [comment]
I have already imported all classes from your library, I think..

Look at the whole code:
```java
import android.os.Bundle;
import android.view.View;
import java.util.ArrayList;
import android.support.v4.app.Fragment;
import android.support.v4.view.ViewPager;
import android.support.annotation.Nullable;
import android.support.v4.app.FragmentManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.app.AppCompatActivity;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v7.preference.PreferenceScreen;
import android.support.v7.preference.XpPreferenceFragment;
import net.xpece.android.support.preference.ListPreference;
import net.xpece.android.support.preference.CheckBoxPreference;
import net.xpece.android.support.preference.PreferenceCategory;


public class MainActivity extends AppCompatActivity {

    private static ArrayList<Fragment> FRAGMENTS_LIST = new ArrayList<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ViewPager mViewPager = (ViewPager) findViewById(R.id.viewPager);
        FragmentPagerAdapter mAdapter = new Adapter(getSupportFragmentManager());
        FRAGMENTS_LIST.add(new PreferencesFragment());
        mViewPager.setAdapter(mAdapter);
    }

    private static class Adapter extends FragmentPagerAdapter {

        Adapter(FragmentManager fragmentManager) {
            super(fragmentManager);
        }

        @Override
        public int getCount() {
            return FRAGMENTS_LIST.size();
        }

        @Override
        public Fragment getItem(int position) {
            return FRAGMENTS_LIST.get(position);
        }

    }

    public static class PreferencesFragment extends XpPreferenceFragment {

        @Override
        public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
            super.onViewCreated(view, savedInstanceState);
            RecyclerView mRecyclerView = getListView();
            mRecyclerView.setFocusable(false);
        }

        @Override
        public void onCreatePreferences2(Bundle savedInstanceState, String rootKey) {
            addPreferencesFromResource(R.xml.preferences_container);

            PreferenceScreen mPreferenceScreen = getPreferenceScreen();

            PreferenceCategory category = new PreferenceCategory(mPreferenceScreen.getContext());
            category.setTitle("Preference Category");

            mPreferenceScreen.addPreference(category);

            CheckBoxPreference checkBoxPreference = new CheckBoxPreference(mPreferenceScreen.getContext());
            checkBoxPreference.setTitle("CheckBox Title");
            checkBoxPreference.setSummary("CheckBox Summary");

            category.addPreference(checkBoxPreference);

            ListPreference listPreference = new ListPreference(mPreferenceScreen.getContext());
            listPreference.setTitle("List Title");
            listPreference.setSummary("%s");
            String[] entries = new String[] {"Entry 1", "Entry 2", "Entry 3"};
            String[] entryValues = new String[] {"1", "2", "3"};
            listPreference.setEntries(entries);
            listPreference.setEntryValues(entryValues);

            category.addPreference(listPreference);
        }

    }

}
```

**Comment by consp1racy** [comment]
OK, found it. Dialog preferences have to have a unique key. Use `setKey(String)` to assign it at runtime.

**Comment by goldmont** [comment]
Solved! Thank you so much.
