### ISSUE TITLE
Add header at runtime throws NPE

### ISSUE THREAD

**Issue by tcqq** [consp1racy/android-support-preference#80]
If i only add one xml, and add a fakeHeader at the same time，app will error

This is add the code：

        PreferenceCategory fakeHeader = new PreferenceCategory(getPreferenceManager().getContext());
        fakeHeader.setTitle(R.string.pref_header_notifications);
        getPreferenceScreen().addPreference(fakeHeader);
        addPreferencesFromResource(R.xml.pref_notification);

This is error log：

  Process: net.xpece.android.support.preference.sample, PID: 14352
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{net.xpece.android.support.preference.sample/net.xpece.android.support.preference.sample.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.preference.PreferenceScreen.addPreference(android.support.v7.preference.Preference)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.preference.PreferenceScreen.addPreference(android.support.v7.preference.Preference)' on a null object reference
                                                       at net.xpece.android.support.preference.sample.SettingsFragment.onCreatePreferences2(SettingsFragment.java:136)
                                                       at android.support.v7.preference.XpPreferenceFragment.onCreatePreferences(XpPreferenceFragment.java:54)
                                                       at android.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:223)
                                                       at android.support.v4.app.Fragment.performCreate(Fragment.java:2172)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1243)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(FragmentManager.java:2323)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2136)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1998)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
                                                       at android.app.Activity.performStart(Activity.java:6992)

**Comment by tcqq** [comment]
If i modify the code into the following code：

    addPreferencesFromResource(R.xml.pref_notification);  
    PreferenceCategory fakeHeader = new PreferenceCategory(getPreferenceManager().getContext());
    fakeHeader.setTitle(R.string.pref_header_notifications);
    getPreferenceScreen().addPreference(fakeHeader);

App will not be error，but fakeHeader will show bottom

**Comment by consp1racy** [comment]
The first time: `getPreferenceScreen()` returns null until you call `setPreferenceScreen(...)`. This is also done for you if you use `addPreferencesFromXml(...)`.

Why don't you add the header in XML?

```
<PreferenceScreen>
    <PreferenceCategory android:title="Title">
        <!-- Preferences. -->
    </PreferenceCategory>
</PreferenceScreen>
```

**Comment by tcqq** [comment]
“Why don't you add the header in XML?”
-Because the data is dynamically obtained from the server

What should I do add header?

**Comment by consp1racy** [comment]
I see, what about this?

    final Context preferenceContext = getPreferenceManager().getContext();
    final PreferenceScreen defaultPreferenceScreen = getPreferenceManager().createPreferenceScreen();
    setPreferenceScreen(defaultPreferenceScreen);

Do it before calling `getPreferenceScreen()`. Then you can continue as you did originally.

**Comment by tcqq** [comment]
thanks
