### ISSUE TITLE
Crash: java.lang.NullPointerException: Attempt to read from field 'boolean net.xpece.android.support.preference.RingtonePreference.i'

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#87]
1.3.1
Just noticed a few crashes with this stack trace:
```java
Caused by java.lang.NullPointerException: Attempt to read from field 'boolean net.xpece.android.support.preference.RingtonePreference.i' on a null object reference
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.net.xpece.android.support.preference.RingtonePreference.getShowDefault(XpRingtonePreferenceDialogFragment.java:2165)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3176)
       at android.support.v4.app.FragmentActivity.android.support.v4.app.FragmentController.dispatchCreate(FragmentActivity.java:7181)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
       at .SettingsActivity.onCreate(SettingsActivity.java:83)
       at android.app.Activity.performCreate(Activity.java:6876)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5382)
       at android.app.ActivityThread.access$1200(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

![image](https://user-images.githubusercontent.com/6302839/35569276-1627d464-05cc-11e8-8e52-abca16be27b6.png)

Can't reproduce this. Can you please look into this?

Thanks

**Comment by consp1racy** [comment]
Hmm, go to system developer settings and tick Don't keep activities (all the way down). Then go to your preference activity, open ringtone picker preference, press Home button, then go back to your app through recents screen. If it crashes, post the stack trace; if it doesn't crash, let me know.

**Comment by dirkam** [comment]
It doesn't crash.

**Comment by consp1racy** [comment]
I think I got it. The dialog fragment is created before the preference fragment after a configuration change. If I delay the code in XpRingtonePreferenceDialogFragment#onCreate, I should be able to fix it.

**Comment by consp1racy** [comment]
Will be in the next version.

Please follow https://github.com/consp1racy/android-support-preference/issues/92, this should get rid of all the problems with ringtone picker.

Also have a look at https://github.com/consp1racy/android-support-preference/issues/93, you seem to have a considerable user base, I'd be very happy if you used this, so we can get rid of any remaining issues in the library.

**Comment by dirkam** [comment]
Thanks.
Sure, will look into this and try to include in next version of the app.

**Comment by dirkam** [comment]
What's the best place to register the error listener `XpSupportPreferencePlugins.registerErrorInterceptor()`?
Is it OK to do it in Settings Activity's `onCreate()`?

**Comment by consp1racy** [comment]
Custom Application class is the best candidate, I think.

You can do it in the Activity, but make sure you only register the listener once (use a static boolean).
