### ISSUE TITLE
SortCursor crash java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)'

### ISSUE THREAD

**Issue by dirkam** [consp1racy/android-support-preference#88]
As discussed in #62 

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
       at net.xpece.android.support.preference.SortCursor.(SortCursor.java:82)
       at net.xpece.android.support.preference.RingtoneManagerCompat.getCursor(RingtoneManagerCompat.java:121)
       at net.xpece.android.support.preference.XpRingtonePreferenceDialogFragment.onCreate(XpRingtonePreferenceDialogFragment.java:164)
       at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Version 1.3.1

Happens on different devices and OS versions (very rare crash).

![image](https://user-images.githubusercontent.com/6302839/35636611-01657fa4-06b2-11e8-9a3a-cbb8d6709d32.png)

Thank you

**Comment by consp1racy** [comment]
I'll treat null as empty string when sorting. Let's see what else this breaks...

This will be in 2.0.2 sometime next week.
